services:
  db:
    image: postgres:latest

    ports:
      - "5432:5432"

    restart: always

    environment:
      POSTGRES_PASSWORD: "changemeinerad!"

  adminer:
    image: adminer:latest

    restart: always

    ports:
      - "8888:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:latest

    ports:
      - "9090:8080"

    restart: always

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"

    command:
      - start-dev
      - --db=dev-file
